# Data Cleaning 2 and models

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score
import sklearn
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

In [4]:
# Read the csv with the train data with dummies

train_dummy=pd.read_csv("../input/train_dummy.csv")

In [62]:
# Read the csv with the predict data with dummies

predict_dummy=pd.read_csv("../input/predict_dummy.csv")
predict=pd.read_csv("../input/predict.csv", index_col="id")

In [63]:
predict_dummy

,id,carat,depth,table,x,y,z,cut_Good,cut_Ideal,cut_Premium,...,color_H,color_I,color_J,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0,0.45,62.8,58.0,4.88,4.84,3.05,0,0,1,...,0,0,0,0,1,0,0,0,0,0
1,1,1.23,61.0,56.0,6.96,6.92,4.23,0,1,0,...,1,0,0,0,1,0,0,0,0,0
2,2,0.33,61.8,55.0,4.46,4.47,2.76,0,1,0,...,0,1,0,1,0,0,0,0,0,0
3,3,0.51,58.0,60.0,5.29,5.26,3.06,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4,4,0.40,62.2,59.0,4.71,4.74,2.94,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.30,62.2,57.0,4.25,4.27,2.65,0,0,0,...,0,1,0,0,1,0,0,0,0,0
13481,13481,1.01,62.3,55.0,6.40,6.44,4.00,0,1,0,...,0,0,1,0,0,0,0,1,0,0
13482,13482,0.33,61.9,55.0,4.43,4.46,2.75,0,1,0,...,0,0,0,0,0,0,0,0,1,0
13483,13483,0.30,59.3,59.0,4.42,4.38,2.61,0,0,1,...,0,0,0,0,0,0,0,1,0,0
13484,13484,1.15,62.6,57.0,6.73,6.69,4.20,0,0,1,...,0,1,0,0,0,1,0,0,0,0

## Cleaning data 2

In [5]:
# I take the dataset with the dummies and only drop column x

In [6]:
train_dropped_x=train_dummy.drop(["x"], axis=1)
train_dropped_x

,id,carat,depth,table,y,z,price,cut_Good,cut_Ideal,cut_Premium,...,color_H,color_I,color_J,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0,0.50,62.3,55.0,5.07,3.17,1845,0,1,0,...,0,0,0,0,0,0,0,1,0,0
1,1,1.54,63.6,60.0,7.33,4.65,10164,1,0,0,...,0,1,0,0,0,0,1,0,0,0
2,2,1.32,61.7,60.0,7.01,4.31,5513,0,0,0,...,0,0,1,0,0,1,0,0,0,0
3,3,1.20,62.1,55.0,6.79,4.23,5174,0,1,0,...,0,1,0,0,1,0,0,0,0,0
4,4,1.73,61.2,60.0,7.65,4.69,10957,0,0,1,...,0,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,40450,0.40,62.9,58.0,4.72,2.96,687,0,0,0,...,0,0,0,0,1,0,0,0,0,0
40451,40451,0.95,62.9,58.0,6.21,3.92,3984,0,0,1,...,1,0,0,0,1,0,0,0,0,0
40452,40452,0.63,61.2,56.0,5.51,3.39,2182,0,1,0,...,0,0,0,0,0,0,0,1,0,0
40453,40453,1.22,63.8,55.0,6.71,4.30,7201,1,0,0,...,1,0,0,0,0,0,0,1,0,0
40454,40454,0.32,60.3,60.0,4.42,2.67,972,0,0,1,...,0,0,0,0,0,0,0,1,0,0

#  Models

## Linear Regression

In [7]:
def check_model(X_train, y_train, model, X_test, y_test):
    model.fit(X_train,y_train)
    y_pred_train=model.predict(X_train)
    y_pred_test=model.predict(X_test)
    
    r2_sc_train=r2_score(y_train, y_pred_train)
    r2_sc_test=r2_score(y_test, y_pred_test)
    rmse_train=(mean_squared_error(y_train, y_pred_train))**0.5
    rmse_test=(mean_squared_error(y_test, y_pred_test))**0.5
    
    return f"r2_score of the train data: {r2_sc_train}, r2_score of the test data: {r2_sc_test}, rmse of the train data: {rmse_train}, rmse of the test data: {rmse_test}"

In [8]:
# Separate into train and test
# Try with 80% data train and 25% data test

y=train_dropped_x["price"]
X=train_dropped_x.drop(columns=["price"])

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [14]:
# Apply and check the Linear Regression model

lr=LinearRegression()
check_model(X_train, y_train, lr, X_test, y_test)

'r2_score of the train data: 0.9192870760743762, r2_score of the test data: 0.9200162362713582, rmse of the train data: 1140.308410195826, rmse of the test data: 1130.4349523725161'

In [10]:
# Cross validation with train

In [15]:
scores = cross_val_score(lr, X_train, y_train, cv=3, scoring="neg_root_mean_squared_error")
scores

array([-1128.80781994, -1123.89487642, -1186.19555857])

The values obtained are too high

## K Neighbors Regression

In [17]:
# Apply and check the model

neigh = KNeighborsRegressor(n_neighbors=2)
check_model(X_train, y_train, neigh, X_test, y_test)

'r2_score of the train data: 0.7202486088909745, r2_score of the test data: 0.029717605640894318, rmse of the train data: 2122.9360629418975, rmse of the test data: 3937.256734750497'

In [18]:
# Cross validation
scoresKN = cross_val_score(neigh, X_train, y_train, cv=3, scoring="neg_root_mean_squared_error")
scoresKN

array([-4206.91629982, -4214.59065961, -4258.68679133])

The values are very high

## Random Forest

In [20]:
# Apply and check the model

ranf = RandomForestRegressor()
check_model(X_train, y_train, ranf, X_test, y_test)

'r2_score of the train data: 0.9962304997340476, r2_score of the test data: 0.9722755382914507, rmse of the train data: 246.42948891984835, rmse of the test data: 665.5431536876376'

In [21]:
# Cross validation
scoresRF= cross_val_score(ranf, X_train, y_train, cv=3, scoring="neg_root_mean_squared_error")
scoresRF

array([-688.44797386, -713.14883295, -730.78570802])

Tha values for rmse are similar to the one obtained with the model, so I select this as a submission

### Test 3 for Kaggle

In [64]:
# Drop column x in predict

predict_dropped_x=predict_dummy.drop(columns="x", axis=1)
predict_dropped_x

,id,carat,depth,table,y,z,cut_Good,cut_Ideal,cut_Premium,cut_Very Good,...,color_H,color_I,color_J,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0,0.45,62.8,58.0,4.84,3.05,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
1,1,1.23,61.0,56.0,6.92,4.23,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0
2,2,0.33,61.8,55.0,4.47,2.76,0,1,0,0,...,0,1,0,1,0,0,0,0,0,0
3,3,0.51,58.0,60.0,5.26,3.06,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4,4,0.40,62.2,59.0,4.74,2.94,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.30,62.2,57.0,4.27,2.65,0,0,0,1,...,0,1,0,0,1,0,0,0,0,0
13481,13481,1.01,62.3,55.0,6.44,4.00,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
13482,13482,0.33,61.9,55.0,4.46,2.75,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
13483,13483,0.30,59.3,59.0,4.38,2.61,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
13484,13484,1.15,62.6,57.0,6.69,4.20,0,0,1,0,...,0,1,0,0,0,1,0,0,0,0

In [65]:
X_test_pred=predict_dropped_x

In [66]:
y_pred_predict=ranf.predict(X_test_pred)
y_pred_predict

array([ 882.91, 6286.69,  746.64, ...,  928.26,  580.04, 4176.88])

In [67]:
predict["price"]=y_pred_predict
predict

       carat        cut color clarity  depth  table     x     y     z    price
id
0       0.45    Premium     E     SI1   62.8   58.0  4.88  4.84  3.05   882.91
1       1.23      Ideal     H     SI1   61.0   56.0  6.96  6.92  4.23  6286.69
2       0.33      Ideal     I      IF   61.8   55.0  4.46  4.47  2.76   746.64
3       0.51    Premium     D     VS2   58.0   60.0  5.29  5.26  3.06  1793.01
4       0.40    Premium     E     VS2   62.2   59.0  4.71  4.74  2.94   932.16
...      ...        ...   ...     ...    ...    ...   ...   ...   ...      ...
13480   0.30  Very Good     I     SI1   62.2   57.0  4.25  4.27  2.65   425.33
13481   1.01      Ideal     J     VS2   62.3   55.0  6.40  6.44  4.00  4349.25
13482   0.33      Ideal     F    VVS1   61.9   55.0  4.43  4.46  2.75   928.26
13483   0.30    Premium     G     VS2   59.3   59.0  4.42  4.38  2.61   580.04
13484   1.15    Premium     I     SI2   62.6   57.0  6.73  6.69  4.20  4176.88

[13485 rows x 10 columns]

In [69]:
predict["price"].to_csv("../output/test3.csv")

# Decision Tree

In [23]:
# Apply and check the model

dtr = DecisionTreeRegressor()
check_model(X_train, y_train, dtr, X_test, y_test)

'r2_score of the train data: 1.0, r2_score of the test data: 0.9476079021693238, rmse of the train data: 0.0, rmse of the test data: 914.90826965469'

In [ ]:
# Overfitted

In [ ]:
# GridSearchCV to find the best parameters to the decision tree regressor

In [25]:
params = {'min_samples_leaf':np.arange(20,50,5),
          'min_samples_split':np.arange(20,50,5),
          'max_depth':np.arange(3,6),
          'min_weight_fraction_leaf':np.arange(0,0.4,0.1)}

In [26]:

grid = GridSearchCV(
     estimator=DecisionTreeRegressor(),
     param_grid=params,
     verbose=3,
     scoring="neg_root_mean_squared_error",
     return_train_score=True
)

In [ ]:
grid.fit(X_train,y_train)

In [28]:
grid.best_estimator_.predict(X_test)

array([15396.35032538,  1863.9345521 ,  1863.9345521 , ...,
        6800.36639238,  2919.97286477,  8208.95774648])

In [29]:
grid.best_estimator_

DecisionTreeRegressor(max_depth=5, min_samples_leaf=30, min_samples_split=20)

In [34]:
grid.best_score_

-1241.333298692898

In [30]:
dtr = DecisionTreeRegressor(min_samples_leaf=30,
                            min_samples_split=20,
                            max_depth=5)
check_model(X_train, y_train, dtr, X_test, y_test)

'r2_score of the train data: 0.9077389401140066, r2_score of the test data: 0.907850553631208, rmse of the train data: 1219.1580395898993, rmse of the test data: 1213.3637726410395'

Too high scores for rmse

# Epsilon-Support Vector Regression

### Epsilon-Support Vector Regression with 25% data in test

In [32]:
# Apply and check the model

esvr=SVR()
check_model(X_train, y_train, esvr, X_test, y_test)

'r2_score of the train data: -0.14499770162677916, r2_score of the test data: -0.1452024312811746, rmse of the train data: 4294.900378041618, rmse of the test data: 4277.458351306098'

Too high rmse